ktor:
  deployment:
    port: 8079

  application:
    modules:
      - solutions.dft.ApplicationKt.main

  database:
    driverClassName: "org.postgresql.Driver"
    jdbcUrl: "jdbc:postgresql://localhost:5432/tasks"
    maximumPoolSize: 3
    isAutoCommit: false
    transactionIsolation: "TRANSACTION_READ_COMMITTED"
    username: "postgres"
#    password: "postgres"
    password: "mysecretpassword"