version: '3.8'

services:

  dft-postgres:
    container_name: dft-postgres
    image: postgres:15
    volumes:
      - ./start-db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
#      - POSTGRES_DB=dft-tasks


